### ISSUE TITLE
save on filesystem

### ISSUE THREAD

**Issue by khalidaboelmagd** [unibet/oracle-imagecopy-backup#5]
can we don't use any type of storage and create it on file system ??

**Comment by ilmarkerm** [comment]
With plain filesystem you can just use RMAN incrementally refreshed image copies, but you are loosing all backup history. With plain filesystem RMAN backupsets are more useful. These scripts make sense only if you have a capable NAS.

**Comment by khalidaboelmagd** [comment]
thanks for your reply,

when i run "SELECT MIN(snaptime) restore_from_snapshot FROM snapshots WHERE snaptime > recoverytime;" 
to get the snapshots I've , it stat that the table doesn't exist

                                                *
ERROR at line 1:
ORA-00942: table or view does not exist

I've DB 19c

**Comment by ilmarkerm** [comment]
Documentation says this SQL statement is "In pseudo SQL code" - pseudo SQL code, just to illustrate the point.
