### ISSUE TITLE
how to get  list of times that I can restore DB to ?!!

### ISSUE THREAD

**Issue by khalidaboelmagd** [unibet/oracle-imagecopy-backup#6]
Is there a way to get which times I can restore DB to?

**Comment by ilmarkerm** [comment]
Assuming you have archivelogging enabled and one archivelog destination is in backup area - to any point in time after the oldest existing snapshot.

**Comment by khalidaboelmagd** [comment]
I'm not able to do so, below what I did,

Restore database to time point: (yyyy-mm-dd hh24:mi:ss) 2021-11-16 14:20:00

Database unique name: FOREVER
Oracle home: /u01/app/oracle/19.0.0/db_1
Clone mount path: /backup
Target instance SID: FOR
Restore target time UTC: 2021-11-16 10:20:00+00:00
Restore target time local: 2021-11-16 14:20:00+04:00
Restored from snapshot: FOREVER-20211116T141735

Are these parameters correct? (y/n) y

and then below error appears 

archived log for thread 1 with sequence 30 is already on disk as file /backup/FOREVER/archivelog/1_30_1088769683.dbf
archived log for thread 1 with sequence 31 is already on disk as file /backup/FOREVER/archivelog/1_31_1088769683.dbf
archived log for thread 1 with sequence 32 is already on disk as file /backup/FOREVER/archivelog/1_32_1088769683.dbf
archived log for thread 1 with sequence 33 is already on disk as file /backup/FOREVER/archivelog/1_33_1088769683.dbf
archived log file name=/backup/FOREVER/archivelog/1_30_1088769683.dbf thread=1 sequence=30
archived log file name=/backup/FOREVER/archivelog/1_31_1088769683.dbf thread=1 sequence=31
archived log file name=/backup/FOREVER/archivelog/1_32_1088769683.dbf thread=1 sequence=32
archived log file name=/backup/FOREVER/archivelog/1_33_1088769683.dbf thread=1 sequence=33
unable to find archived log
archived log thread=1 sequence=34
released channel: c1
RMAN-00571: ===========================================================
RMAN-00569: =============== ERROR MESSAGE STACK FOLLOWS ===============
RMAN-00571: ===========================================================
RMAN-03002: failure of recover command at 11/16/2021 14:19:40
RMAN-06054: media recovery requesting unknown archived log for thread 1 with sequence 34 and starting SCN of 2333022

**Comment by khalidaboelmagd** [comment]
I fixed it, I needed to create new clone first using ./zsnapper.py FOR create
